# -*- coding: utf-8 -*-
"""pbf1_Deyvan Loxefal_121450148.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bvGgQB8uNMXrt4lDTiuxXJV2FH5wKhRV

Deyvan Loxefal

121450148

Sains Data

# 1. Jelaskan menggunakan tabel mengenai kelebihan dan kekurangan paradigma procedural dibandingkan dengan object oriented (minimal 3) !

| Kelebihan | Kelemahan |
|------------|--------------| 
| Cocok untuk program sederhana | Kurang cocok untuk program kompleks | 
| Lebih mudah dipahami dibandingkan Object Oriented | kurang aman |
| menggunakan memori yang lebih sedikit | fungsi sulit untuk diubah/dimodifikasi |

2. Jelaskan menggunakan tabel mengenai kelebihan dan kekurangan paradigma object oriented dibandingkan dengan functional (minimal 3) !


| Kelebihan | Kelemahan |
|------------|--------------| 
| algoritma lebih jelas dairipada fungsional | program lebih kompleks dan banyak | 
| Cocok untuk program kompleks |  pemakaian momori yang lebih besar |
| reusability(dapat digunakan kembali) | sulit dipahami |

3. Jelaskan menggunakan tabel mengenai kelebihan dan kekurangan paradigma procedural dibandingkan dengan functional (minimal 3) !

|kelebihan | kekurangan |
|-------|-----|
| mudah dipahami |	Memiliki algoritma pemecahan masalah yanag sederhana |
| Memiliki algoritma pemecahan masalah yanag sederhana|	Mungkin dapat bekerja dengan baik pada saat terisolasi tapi tidak pada saat terintegrasi dengan sistem lain. |
|Data bersifat mutable | fungsi sulit untuk diubah/dimodifikasi |

|

# 4. Apa yang dimaksud dengan pure functional programming language?


"Pure functional programming language adalah di mana pada fungsinya menerima parameter sebagai input dan mengembalikan nilai, tanpa mengubah nilai dari variabel manapun"

# 5. Dari bahasa pemrograman FP di slide sebelumnya ( slide 14 ) , manakah yang termasuk pure functional programming language?

 Lisp, Haskell

# 6. Membuat program Simple Password encryption, dengan ketentuan

1. Input password bertipe string dengan batasan panjang password 100 karakter
2. Setiap karakter dari string tersebut diubah menjadi ASCII value
3. Kemudian setiap ASCII value tersebut dikembangkan menjadi 3 value dengan dilakukan operasi berikut:
1. Value pertama dibagi dengan integer 26 kemudian dibulatkan dan dijumlahkan dengan 80 kemudian diubah kembali menjadi karakter
2. Value kedua dihitung sisa bagi dengan 26 kemudian dijumlahkan dengan 80 kemudian diubah kembali menjadi karakter
3. Value ketiga adalah karakter ‘+’ jika value pertama lebih besar dari value kedua, atau value ketiga adalah karakter ‘-’ jika value pertama tidak lebih besar dari value kedua
4. Deretkan value pertama, kedua dan ketiga untuk setiap karakter dalam password tersebut sehingga didapatkan password dalam bentuk baru
"""

def enkripsi(pas):
    if len(pas) > 100:
        return "Kata melebihi batas"
    elif len(pas) < 3: 
        return "kata kurang banyak"
   


    enkripsi_password = ""
    for char in pas:
        ascii_value = ord(char) 
        value_1 = chr(round((ascii_value / 26)) + 80) 
        value_2 = chr((ascii_value % 26) + 80)
        if value_1 > value_2:
            value_3 = '+'; 
        else:
            value_3 = '-'
        enkripsi_password += value_1 + value_2 + value_3
    print(enkripsi_password)
    
   

password = input("Enter Password: ") #contoh "institut teknologi sumatera"
enkripsi(password)

